menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/wise1994
    GitHub: https://github.com/houyonglu
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.svg

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-65933410-1

# Copyright Infomation
startyear: 2017
